CREATE EXTERNAL TABLE IF NOT EXISTS
    mobile_sessions(
        session_start string,
        session_end string,
        visitor_id string,
        session_id string,
        site_mode string,
        pageviews int,
        special_pageviews int,
        entry_uri string,
        entry_referer string,
        exit_uri string)
PARTITIONED BY (
    dt string)
ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION
    'hdfs:///wmf/data/webrequest/mobile/views/sessions'

