#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" Automatically adds Hive partitions based on HDFS directory hierarchy.

Usage: hive-partitioner [options] <camus_destination_path>
    
Options:
    -h --help                       Show this help message and exit.
    -D --database=<dbname>          Hive database name.  [default: default]
    -o --hive-options=<options>     Any valid Hive CLI options you want to pass to Hive commands.
                                    Example: '--auxpath /path/to/hive-serdes-1.0-SNAPSHOT.jar'
"""
__author__ = 'Andrew Otto <otto@wikimedia.org>'

from   datetime import datetime
from   docopt import docopt
import logging
import os
import subprocess
import pprint

from util import HiveUtils, CamusUtils, sh, diffDatewise, interval_hierarchies

pp     = pprint.pprint
logger = logging.getLogger('hive-partitioner')


if __name__ == '__main__':
    # parse arguments
    arguments = docopt(__doc__)
    print(arguments)
    logging.basicConfig(level=logging.DEBUG)

    camus_destination_path = arguments['<camus_destination_path>']
    database               = arguments['--database']
    hive_options           = arguments['--hive-options']

    hive = HiveUtils(database, hive_options)
    camus = CamusUtils(camus_destination_path)

    topics = camus.topics()
    print("Topics: " + ','.join(topics))
    for topic in topics:
        if hive.table_exists(topic):
            interval         = hive.partition_interval(topic)
            hive_partitions  = hive.partitions(topic)
            camus_partitions = camus.partitions(topic, camus_destination_path)

            logger.debug(("Hive Partitions for %s:\n" % topic) + '\n'.join(hive_partitions))
            logger.debug(("Camus Partitions for %s:\n " % topic) + '\n'.join(camus_partitions))
            logger.debug("%s import interval is %s" % (topic, interval))

            # diff the camus and hive partitions
            missing_hive, missing_camus = diffDatewise(camus_partitions, hive_partitions,
                interval_hierarchies[interval]['directory_format'],
                interval_hierarchies[interval]['hive_partition_format'])
            print("Need to create partition for:")
            pp(missing_hive)
