package org.wikimedia.analytics.kraken.funnel;

import java.util.HashMap;
import java.util.regex.Pattern;

public class FunnelNode extends AbstractNode{
	/** The params. */
	public HashMap<String, Pattern> params;

	/**
	 * Instantiates a new node. This constructor does not require the
	 * the useragent string as input.
	 *
	 * @param fproject the project variable as generated by the EventLogging extension.
	 * @param fnamespace the namespace variable as generated by the EventLogging extension.
	 * @param fpage the page variable as generated by the EventLogging extension.
	 * @param fevent the event variable as generated by the EventLogging extension.
	 */
	public FunnelNode(String fproject, Integer fnamespace, Integer fpage, String fevent) {
	}

	/**
	 * Instantiates a new node with useragent information.
	 *
	 * @param fuseragent the useragent variable as obtained from Kraken.
	 * @param fproject the project variable as generated by the EventLogging extension.
	 * @param fnamespace the namespace variable as generated by the EventLogging extension.
	 * @param fpage the page variable as generated by the EventLogging extension.
	 * @param fevent the event variable as generated by the EventLogging extension.
	 */
	public FunnelNode(String fuseragent, String fproject, Integer fnamespace, Integer fpage, String fevent) {
	}

	@Override
	void setProject(String fproject) {
		// TODO Auto-generated method stub

	}

	@Override
	public boolean equals(Node b) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

}
